### ISSUE TITLE
Creation of a RADON-based workspace

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#12]
**ID** | **R-T2.3-12**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to create a RADON-based workspace |
| Requirement | The IDE must provide the opportunity to create a new RADON-based workspace |
| Extended Description | The RADON-based workspace will provide a "stack" having all the tools, plugins and extensions enabled (e.g. Theia IDE, cloning of TOSCA type repo, Winery, Verifcation Tool, Decomposition Tool, etc.) |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Availability of a RADON-based workspace in the IDE |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework a user is able to create a RADON workspace within the RADON IDE starting a RADON Stack. The new implemented RADON Stack  at the moment provides the availability of the following RADON tools: Graphical Modelling Tool, Verification Tool, Decomposition Tool and Defect Prediction Tool. Moreover, a RADON modelling project is available within the RADON workspace

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework we will update the implementation of the RADON Stack so that the user is able to create a RADON workspace within the RADON IDE which, respect the alpha version, provides also the integration of these RADON tools: Continuous Testing Tool, Template Library, Monitoring System and Delivery Toolchain.

**Comment by gcasale** [comment]
Approved

**Comment by sdagostini** [comment]
In the finale release of the RADON integrated framework the implementation of the RADON Stack has been updated to integrated all the expected RADON tools.
