### ISSUE TITLE
Creation of a RADON modelling project

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#13]
**ID** | **R-T2.3-13**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to create a RADON modelling project |
| Requirement | The IDE must provide the opportunity to create a new RADON modelling project |
| Extended Description | The RADON modelling project will provide a directory structure complaint with the graphical modeling tool (GMT, Winery) |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Avalability of a RADON modelling project type in the IDE |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework the RADON modelling project is created by default once  created a new RADON workspace

**Comment by gcasale** [comment]
Approved
