### ISSUE TITLE
Integration of GMT

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#14]
**ID** | **R-T2.3-14**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to launch the GMT from a RADON modelling project |
| Requirement | The IDE must provide support to launch the GMT from a RADON modelling project |
| Extended Description | The GUI provided by the graphical modeling tool (GMT, Winery) will be integrated into the IDE so that will be possible to launch the GMT based on a specific workspace containing a RADON modelling project |
| Affected Tools | IDE, GMT |
| Means of Verification | Integration of the GMT into the IDE and demo based |
| Dependency | R-T4.3-1 |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework the GMT has been integrated on the RADON IDE as a kubernetes component

**Comment by gcasale** [comment]
Approved
