### ISSUE TITLE
Access projects inside a workspace from the GMT

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#15]
|**ID** | **R-T2.3-15**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to access projects inside a workspace from the GMT |
| Requirement | The IDE must support the integration of a Winery plugin in order to navigate from the GMT to the respective workspace where the source code is maintained |
| Extended Description | Winery/GMT will need to register a plugin in order to interact with a workspace (e.g. to open a respective source code editor if someone wants to edit an attached TOSCA code artifact) |
| Priority | Must have |
| Affected Tools | IDE, GMT |
| Means of Verification | Integration of the GMT into the IDE and demo based |
| Dependency | R-T4.3-2, R-T4.3-3|

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the final release of the framework the "jump to code" behavior will be implemented. In particular, 

- A customized Che-Theia editor will be added to the RADON devfile. The custom Che-Theia image includes the Winery extension which permits to navigate from the GMT to the respective workspace where the source code is maintained;
- Users will be able to open from the GMT a new browser tab opening the Che IDE. The Winery extension pre-selects the folder of the respective TOSCA node type or service template and opens the TOSCA file in the IDE.

**Comment by gcasale** [comment]
Approved

**Comment by sdagostini** [comment]
@miwurster This requirement has been implemented with the PR - "Custom Che-Theia editor with Winery extension". I can close the issue.
