### ISSUE TITLE
Synchronization of changes made within the IDE in the GMT and vice versa

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#16]
|**ID** | **R-T2.3-16**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to visualize changes made within the IDE in the GMT and vice versa |
| Requirement | The IDE must support the synchronization of changes made from within IDE with the GMT and vice versa |
| Extended Description | Changes made from within IDE will be synchronized with GMT and vice versa, e.g. when function's source code or a TOSCA definition is changed directly in the workspace, GMT has to highlight that the corresponding entity was modified |
| Priority | Must have |
| Affected Tools | IDE, GMT |
| Means of Verification | Integration of the GMT into the IDE and demo based |
| Dependency | N/A |

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework the synchronization of changes made from within IDE with the GMT is fulfilled with the container-based integration of GMT. In particular:

(1)    all changes from the “project-radon” project are in sync with GMT, as GMT operates directly on these files.
(2)    By referencing business logic artifacts (e.g., function code) as URL-based artifacts in GMT, GMT will download always the latest version during CSAR generation

**Comment by gcasale** [comment]
Approved
