### ISSUE TITLE
Export project capability

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#17]
|**ID** | **R-T2.3-17**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | PORTABILITY |
| User Story | As a Software Developer, I want to export a project for reuse it in other environments |
| Requirement | The IDE must provide the possibility to export projects |
| Extended Description | The IDE will allow to export the chosen projects for reuse them in other environments |
| Affected Tools | IDE |
| Means of Verification | Provision of export capabilities |
| Dependency | N/A |

**Comment by sdagostini** [comment]
The RADON IDE is based on the Eclipse Che technology. This capability has been achieved by means of this underlying technology (i.e. a "Download" command is provided on the user interface to export a project on the file system)

**Comment by gcasale** [comment]
Approved
