### ISSUE TITLE
Support in launching the TOSCA management UI

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#18]
|**ID** | **R-T2.3-18**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to launch the TOSCA management UI from a RADON modelling project |
| Requirement | The IDE must provide support in launching the TOSCA management UI from a RADON modelling project |
| Extended Description |The IDE will provide support to launch the TOSCA management UI provided by Winery from a RADON modelling project inside the workspace in order to edit the related TOSCA entities |
| Affected Tools | IDE, GMT |
| Means of Verification | Integration of the GMT into the IDE and demo based |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework it's possible to launch the TOSCA management UI by means of the GMT integrated on it

**Comment by gcasale** [comment]
Approved
