### ISSUE TITLE
Export the application blueprints as TOSCA CSAR

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#19]
|**ID** | **R-T2.3-19**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | PORTABILITY |
| User Story | As a Software Developer, I want to export the application blueprints as TOSCA CSAR |
| Requirement | The IDE must provide the possibility to export the application blueprints as TOSCA CSAR |
| Extended Description | Using a workspace plugin will be possible to export the application blueprints as TOSCA CSAR |
| Affected Tools | IDE|
| Means of Verification | Export capability of application blueprints as TOSCA CSAR |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework the application blueprints is exported as a TOSCA CSAR and stored within the Eclipse Che’s workspace by means of the GMT integrated on it

**Comment by gcasale** [comment]
Approved
