### ISSUE TITLE
Support of different programming language

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#2]
| **ID** | **R-T2.3-2**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to develop application using Java, Go, Node.js, Python and Ruby programming languages |
| Requirement | The IDE must be able to support the use of Java, Go, Node.js, Python and Ruby programming languages |
| Extended Description | Even if the IDE must not lock-in to particular language, the Java, Go, Node.js, Python and Ruby programming languages must be supported |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Direct implementation on IDE |
| Dependency | N/A |

**Comment by sdagostini** [comment]
The RADON IDE is based on the Eclipse Che technology which provides support for different program languages. In particular, the alpha release of the RADON framework supports the  Java, Go, Node.js and Python programming languages

**Comment by gcasale** [comment]
Approved
