### ISSUE TITLE
Integration of Defect Prediction Tool

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#21]
|**ID** | **R-T2.3-21**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to verify the quality of the developed code (i.e. Infrastructure-as-Code templates/ blueprints) |
| Requirement | The IDE must provide support to launch the DEFECT_PRED_TOOL and to show the state of the infrastructure in a graphical way |
| Extended Description |The DEFECT_PRED_TOOL will be integrated on the IDE in order to support the identification of IaC defects |
| Priority | Must have |
| Affected Tools | IDE, DEFECT_PRED_TOOL |
| Means of Verification | Integration of the DEFECT_PRED_TOOL into the IDE and demo based |
| Dependency |R-T3.4-1, R-T3.4-2 |

**Comment by gcasale** [comment]
Approved
