### ISSUE TITLE
Support in showing monitoring information

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#22]
|**ID** | **R-T2.3-22**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As an Operations Engineer/Release Manager I want to monitor the status of the deployment process |
| Requirement | The IDE must provide support in showing the monitoring information collected by the MONITORING_SYSTEM |
| Extended Description | The IDE will connect to a dashboard to keep users updated on the status of the deployment stages |
| Priority | Must have |
| Affected Tools | IDE, MONITORING_SYSTEM |
| Means of Verification | Connection to the monitoring information from the IDE and demo based |
| Dependency | R-T5.1-3 |

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework we will update the current version of the “RADON menu” che-plugin in order to implement a new command to open the Monitoring Dashboard directly from the RADON menu of the RADON IDE. This new command enables a RADON user to interact with the Monitoring system in order to collect monitoring information.

**Comment by gcasale** [comment]
Approved

**Comment by sdagostini** [comment]
In the final release of the RADON integrated framework the "Open Monitoring Page" option has been added to open the RADON Monitoring Dashboard.
