### ISSUE TITLE
Avalability of a RADON menu

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#23]
|**ID** | **R-T2.3-23**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | USABILITY |
| User Story | As a Software Developer/Operations Engineer/QoS Engineer I want to launch the RADON tools via a dedicated menu |
| Requirement | The IDE must provide a menu in order to use the different RADON tools |
| Extended Description | The IDE will provide a RADON menu from which the integrated RADON tools can be launched |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Availability of the RADON Menu and demo based |
| Dependency | N/A |

**Comment by gcasale** [comment]
Approved
