### ISSUE TITLE
RADON tool UI elements

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#27]
|**ID** | **R-T2.3-24**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | USABILITY |
| User Story | As a Software Developer/Operations Engineer/QoS Engineer I want to interact with the integrated RADON tools via UI elements (e.g. menu, popup window, views, tree)  |
| Requirement | The IDE must provide UI elements  (e.g. menu, popup window, views, tree etc) for the interaction with the integrated RADON tools |
| Extended Description | In order to increase usability, the IDE will support the interaction with the integrated RADON tools using the UI elements (e.g. menu, popup window, views, tree etc) that best fit to the tool's needs |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Demo based |
| Dependency | N/A |

**Comment by sdagostini** [comment]
@gcasale  please approve new requirement.

**Comment by gcasale** [comment]
Can we please mention also menus as one of the feasible UI elemeents?

**Comment by sdagostini** [comment]
The menu UI element is also mentioned in this requirement.

**Comment by sdagostini** [comment]
In the final release of the RADON integrated framework some UI elements has been improved to better interct with he RADON tools.
