### ISSUE TITLE
Integration of the Verification Tool

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#29]
|**ID** | **R-T2.3-26**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to verify that a RADON model conforms to the CDL specification defined by the CDL tool |
| Requirement | The IDE must provide support to launch the Verification Tool in order to suggest corrections or improvements to a RADON model |
| Extended Description | The Verification Tool will be integrated on the IDE in order to verify that a RADON model conforms to the CDL constraints |
| Priority | Must have |
| Affected Tools | IDE, Verification Tool |
| Means of Verification | Integration of the Verification Tool into the IDE and demo based |
| Dependency | |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework a first version of the Verification Tool has been integrated in the IDE by means of a che plugin and a kubernetes component

**Comment by sdagostini** [comment]
@gcasale please approve new requirement

**Comment by gcasale** [comment]
Approved
