### ISSUE TITLE
Customization capabilities

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#3]
| **ID** | **R-T2.3-3**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to provide new capabilities throught custom plug-in development |
| Requirement | The IDE must be extensible by customizing built-in plugins |
| Extended Description | The provision of new editors/wizards, new API's and workspace agents plugins are examples of customization |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Extensibility and customization of the IDE |
| Dependency | N/A |

**Comment by sdagostini** [comment]
The RADON IDE is based on the Eclipse Che technology an extensible and customizable platform. We customized the IDE by means of plugins

**Comment by gcasale** [comment]
Approved
