### ISSUE TITLE
Integration of Decomposition Tool

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#30]
|**ID** | **R-T2.3-27**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to find the optimal decomposition solution for an application based on the microservices architectural style |
| Requirement | The IDE must provide support to launch the Decomposition Tool in order to finding the optimal decomposition solution for an application described by means of a RADON model |
| Extended Description | The Decomposition Tool will be integrated on the IDE in order to finding the optimal decomposition solution for a specified RADON model |
| Priority | Must have |
| Affected Tools | IDE, Decomposition Tool |
| Means of Verification | Integration of the Decomposition Tool into the IDE and demo based |
| Dependency | |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework a first version of theDecomposition Tool has been integrated in the IDE by means of a che plugin

**Comment by sdagostini** [comment]
@gcasale please approve new requirement

**Comment by gcasale** [comment]
Approved
