### ISSUE TITLE
Unable to start new RADON workspace

### ISSUE THREAD

**Issue by Philips-SSP** [radon-h2020/radon-ide#33]
Hi guys,

When I try to open up a new RADON workspace from 'Get Started' by clicking the RADON Stack, the environment won't launch. Clicking other stacks (e.g. Python 3.7) seems to be working fine. Any idea on how to resolve this issue? Also, is there any alternative to launching from the UI that I can try in the meantime?

**Comment by sdagostini** [comment]
@Philips-SSP Hi, yes there is a issue with the "RADON Stack" functionality, we will solve it as soon as possbile. In the mentime you can create a RADON workspace following the procedure described here https://radon-ide.readthedocs.io/en/latest/. In particular, please give a look to the "Create a RADON workspace" section under the "Getting Started" chapter.

**Comment by Philips-SSP** [comment]
Yes that worked, thank you!

> @Philips-SSP Hi, yes there is a issue with the "RADON Stack" functionality, we will solve it as soon as possbile. In the mentime you can create a RADON workspace following the procedure described here https://radon-ide.readthedocs.io/en/latest/. In particular, please give a look to the "Create a RADON workspace" section under the "Getting Started" chapter.

Yes that worked, thank you!
