### ISSUE TITLE
Debugging capabilities

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#4]
| **ID** | **R-T2.3-4**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to to step through the debugging of the application and identify errors |
| Requirement | The IDE must provide debugger functionalities |
| Extended Description | Debugging facilities will allow to navigate the thread of the application code througth common debug operations (i.e. variable watching and substitutions, breakpoints, step into/over) |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Inspection of application code step-by-step |
| Dependency | N/A |

**Comment by sdagostini** [comment]
The RADON IDE is based on the Eclipse Che technology. This capability has been achieved by means of this underlying technology which provides debugger functionalities

**Comment by gcasale** [comment]
Approved
