### ISSUE TITLE
Support of source code editors

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#5]
| **ID** | **R-T2.3-5**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to develop applications using source code editors which simplify and speed up the typing of source code |
| Requirement | The IDE must provide source code editors supporting syntax highlighting, auto-complete and error checking capabilities |
| Extended Description | The writing and editing of source code will be enhanced and simplified throght source code editors with syntax highlighting and auto-complete functionalities |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Direct implementation on IDE |
| Dependency | N/A |

**Comment by sdagostini** [comment]
The RADON IDE is based on the Eclipse Che technology. This capability has been achieved by means of this underlying technology whichprovides code editors and error checking capabilities for the supported programming languages

**Comment by gcasale** [comment]
Approved
