### ISSUE TITLE
Secure application workspaces

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#6]
| **ID** | **R-T2.3-6**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | SECURITY |
| User Story | As a Software Developer, I want to secure application workspaces from unauthorized users |
| Requirement | To secure application and services the IDE must provide identity and access management fuctionalities |
| Extended Description | Authentication and authorization management capabilities will be applied to regulate accesss to different IDE's entities (e.g. workspaces, stacks etc..) |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Support of access control policies |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework, only register user can access to the RADON IDE using username and password credentials

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework we will use Keycloack (i.e. the identity and access management system provided by the Eclipse Che) to secure the interaction with the RADON tools that require identity information (e.g. SaaS xOpera and Monitoring System)

**Comment by gcasale** [comment]
Approved

**Comment by sdagostini** [comment]
In the final release of the RADON integrated framework Keycloack has been used to secure the interaction with the SaaS xOpera and Monitoring System tools.
