### ISSUE TITLE
Integration of TESTING_TOOL

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#7]
| ID | R-T2.3-7| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a QoS Engineer, I want to be able to maintain my continuous tests |
| Requirement | The IDE must provide support in launching the TESTING_TOOL and to trigger the execution of tests |
| Extended Description | The TESTING_TOOL will be integrated on the IDE in order to support the annotation of the RADON models with test-related information |
| Priority | Must have |
| Affected Tools | IDE, TESTING_TOOL |
| Means of Verification | Tests and demo based on the case study scenarios |
| Dependency | R-T3.3-6, R-T3.3-7,R-T.3.3-14, R-T.3.3-14 |

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework the Continuous Testing Tool will be integrated in the RADON IDE. A RADON user will be able to execute tests specified in the RADON models.

**Comment by gcasale** [comment]
Approved

**Comment by sdagostini** [comment]
In the final release of the RADON integrated framework the integration of the CTT has been improved.
