### ISSUE TITLE
Access to test reports

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#8]
| **ID** | **R-T2.3-8**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a QoS Engineer, I want to receive test results in the form of a comprehensive report |
| Requirement | The IDE must provide access to a report based on the results received from the TESTING_TOOL |
| Extended Description | The IDE must be able to retrieve the results of the tests from the TESTING_TOOL and show them with a graphical representation and textual explanation of the data |
| Priority | Must have |
| Affected Tools | IDE, TESTING_TOOL |
| Means of Verification | Tests and demo based on the case study scenarios |
| Dependency | R-T3.3-5, R-T3.3-7, R-T.3.3-13 |

**Comment by sdagostini** [comment]
@gcasale please review and approve.

In the beta release of the framework the results of the test configurations executed by a RADON user are stored and visible in a project folder of the RADON workspace.

**Comment by gcasale** [comment]
Approved
