### ISSUE TITLE
Access to the shared repositories

### ISSUE THREAD

**Issue by sdagostini** [radon-h2020/radon-ide#9]
**ID** | **R-T2.3-9**| 
| --- | --- |
| Section | WP2: Integrated Framework |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to store and share the applicatication code and the RADON models in a repository |
| Requirement | The IDE must provide access to the shared repositories of code and RADON models |
| Extended Description | The shared repositories of code and RADON models will reside externally to the IDE and will be accessed by developers through appropriate tools (e.g. GIT) |
| Priority | Must have |
| Affected Tools | IDE |
| Means of Verification | Access to the shared repositories |
| Dependency | N/A |

**Comment by sdagostini** [comment]
In the alpha release of the RADON framework the shared repositories of code and the RADON models can be accessed by developers within the IDE through the Git capabilities made available by the underlying Eclipse Che technology

**Comment by gcasale** [comment]
Approved
